export const HOME = "/"
export const ESPECIES = "/especies"
export const ROLES = "/roles"
export const EMPLEADOS = "/empleados"
export const INICIAR_SESION = "/login"
export const PROVEEDORES = "/proveedores"
export const DASHBOARD = "/dashboard"
export const SUCURSALES = "/sucursales"
