export const HOME = "/"
export const ESPECIES = "/especies"
export const ROLES = "/roles"
export const EMPLEADOS = "/empleados"
export const INICIAR_SESION = "/login"
export const PROVEEDORES = "/proveedores"
export const DASHBOARD = "/dashboard"
export const SUCURSALES = "/sucursales"
export const CLIENTES = "/clientes"
export const VENTAS = "/ventas"
export const RAZAS = "/razas"
export const HISTORIAS_CLINICAS = "/historiaClinica"
export const DETALLE_HISTORIAS_CLINICAS = "/detalleHistoriaClinica"
export const MASCOTAS = "/mascotas"
export const PRODUCTOS = "/productos"
export const CATEGORIAS = "/categorias"
export const COMPRAS = "/compras"
export const TURNOS = "/turnos"


