// // aca van los endpoints(controladores) del backend
// export const ejemplo = 'http://localhost:8000/ejemplo';
// export const ESPECIES = 'http://localhost:8000/especies';
// export const ROLES = 'http://localhost:8000/roles';
// export const empleados = 'http://localhost:8000/empleados'
// export const proveedores = 'http://localhost:8000/proveedores'
// export const SUCURSALES = 'http://localhost:8000/sucursales';
// export const CLIENTES = 'http://localhost:8000/clientes';
// export const VENTAS = 'http://localhost:8000/ventas';
// export const detallesVentas = 'http://localhost:8000/detallesVentas';
// export const clientes = 'http://localhost:8000/clientes';
// export const razas = 'http://localhost:8000/razas';
// export const historiasClinicas = 'http://localhost:8000/historiaClinica';
// export const detalleHistoriasClinicas = 'http://localhost:8000/detalleHistoriaClinica';
// export const mascotas = 'http://localhost:8000/mascotas'
// export const productos = 'http://localhost:8000/productos'
// export const dashboard = 'http://localhost:8000/dashboard'
// export const categorias = 'http://localhost:8000/categorias'
// export const TURNOS = 'http://localhost:8000/turnos'
// export const STOCK = 'http://localhost:8000/stock'
// export const informes = 'http://localhost:8000/informes'
// aca van los endpoints(controladores) del backend
export const ejemplo = 'https://softvet-backend.onrender.com/ejemplo';
export const ESPECIES = 'https://softvet-backend.onrender.com/especies';
export const ROLES = 'https://softvet-backend.onrender.com/roles';
export const empleados = 'https://softvet-backend.onrender.com/empleados'
export const proveedores = 'https://softvet-backend.onrender.com/proveedores'
export const SUCURSALES = 'https://softvet-backend.onrender.com/sucursales';
export const CLIENTES = 'https://softvet-backend.onrender.com/clientes';
export const VENTAS = 'https://softvet-backend.onrender.com/ventas';
export const detallesVentas = 'https://softvet-backend.onrender.com/detallesVentas';
export const clientes = 'https://softvet-backend.onrender.com/clientes';
export const razas = 'https://softvet-backend.onrender.com/razas';
export const historiasClinicas = 'https://softvet-backend.onrender.com/historiaClinica';
export const detalleHistoriasClinicas = 'https://softvet-backend.onrender.com/detalleHistoriaClinica';
export const mascotas = 'https://softvet-backend.onrender.com/mascotas'
export const productos = 'https://softvet-backend.onrender.com/productos'
export const dashboard = 'https://softvet-backend.onrender.com/dashboard'
export const categorias = 'https://softvet-backend.onrender.com/categorias'
export const TURNOS = 'https://softvet-backend.onrender.com/turnos'
export const STOCK = 'https://softvet-backend.onrender.com/stock'
export const informes = 'https://softvet-backend.onrender.com/informes'
